Connect ceremony details to contentful natalie
Code-the-Change-YYC/hackathon-management-tool pull request #142
Opened 2024-10-30 20:30 UTC by burtonjong

2024-10-30 20:32 UTC, burtonjong commented
rebased off #120 i believe

2024-10-31 02:28 UTC, justin-phxm requested changes
Lots of good stuff but maybe we can wait until we get my PRs in before continuing on this one. There is a considerable amount of overlap and optimizations that can still be done.

2024-10-31 02:28 UTC, justin-phxm commented on src/app/contentfulTypes.ts
I don't believe we need to create a new contentful type to do this. Lets just add an extra field onto the HackathonDetails Type.

2024-10-31 02:28 UTC, justin-phxm commented on src/app/actions.ts
I have an upgrade in #147 that will prevent the need to do this

2024-10-31 02:28 UTC, justin-phxm commented on src/components/Dashboard/ImportantInformation.tsx
an upgrade in #147 will fix this. css changes?

2024-10-31 02:28 UTC, justin-phxm commented on src/components/Dashboard/JudgingInfo.tsx
>    const href = "#";
Do we want to leave this href blank?

2024-10-31 02:28 UTC, justin-phxm commented on src/components/Dashboard/JudgingInfo.tsx
We should take advantage of NextJS SSR by breaking this component down into separate smaller components.

Here are some example of me using it:
https://github.com/Code-the-Change-YYC/hackathon-management-tool/blob/74c388e4859b30bfdfdd1cce27cc5b60ebb97b77/src/components/Dashboard/TotalTeams.tsx#L8

https://github.com/Code-the-Change-YYC/hackathon-management-tool/blob/74c388e4859b30bfdfdd1cce27cc5b60ebb97b77/src/components/Dashboard/TotalParticipants.tsx#L8

https://github.com/Code-the-Change-YYC/hackathon-management-tool/blob/74c388e4859b30bfdfdd1cce27cc5b60ebb97b77/src/components/Dashboard/NumFoodTickets.tsx#L11-L12

2024-10-31 02:28 UTC, justin-phxm commented on src/components/Dashboard/JudgingInfo.tsx
Also if we turn this to a server component, consider wrapping in a SuspenseWrapper.

https://github.com/Code-the-Change-YYC/hackathon-management-tool/blob/74c388e4859b30bfdfdd1cce27cc5b60ebb97b77/src/components/SuspenseWrapper.tsx#L5

2024-11-06 05:56 UTC, burtonjong commented on src/components/Dashboard/JudgingInfo.tsx
Make a ticket / issue and a recruit or someone else can finish this later as its low prio

2024-11-07 02:26 UTC, ideen1 approved these changes
LGTM

2024-11-07 02:41 UTC, merged