Hmt 3 navbar
Code-the-Change-YYC/hackathon-management-tool pull request #2
Opened 2024-02-19 21:04 UTC by justin-phxm

![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/113923596/5d0cbf47-3738-4fee-94fe-119004421c50)

Added the navBar component

![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/113923596/b0dcffb0-173d-4986-a398-dc7caebc8b9c)

use these variables to test the conditional rendering.
```
const isSignedIn = true;
const hasTeam = true;
```

2024-02-23 01:43 UTC, justin-phxm commented on public/MissingProfile.svg
I was thinking that if we used a social sign on library or google auth, we could import their profile picture. If we used an icon, I am not sure if that would be possible.

2024-02-29 06:21 UTC, ideen1 commented
This looks good, just the svgs need to be cropped closer to the image so there's no border.

2024-02-29 06:21 UTC, ideen1 requested changes
Profile SVG should have no border around it, otherwise LGTM!!

2024-03-01 01:56 UTC, justin-phxm commented
> Profile SVG should have no border around it, otherwise LGTM!!

updated!
![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/113923596/f3db50a9-52fd-4add-bd1f-b2ca953f7b47)

2024-03-01 08:29 UTC, ideen1 approved these changes

2024-03-05 07:18 UTC, ideen1 commented
Looks good! It can be merged in

2024-03-07 16:22 UTC, merged