Frontend for reset page
Code-the-Change-YYC/hackathon-management-tool pull request #72
Opened 2024-07-18 23:20 UTC by burtonjong

Didnt test it yet but the input looks good to me

didnt use react hook form yet either but that can be done later

only problem maybe is this:

```
{
    "scoreComponents": "[\n              {\n                id: \"Cool beans, this should be a uuid\",\n                friendlyName: \"no name for you\",\n                isSidepot: false\n              },\n              {\n                id: \"uuid v2\",\n                friendlyName: \"I love eating free food\",\n                isSidepot: false\n              }\n            ]",
    "scoringSidepots": "[\n              {\n                id: \"Cool beans, this should be a uuid\",\n                friendlyName: \"no name for you\",\n                isSidepot: false\n              },\n              {\n                id: \"uuid v2\",\n                friendlyName: \"I love eating free food\",\n                isSidepot: false\n              }\n            ]",
    "startDate": "2024-08-02",
    "endDate": "2024-08-09",
    "resetUsers": true,
    "resetRooms": true,
    "resetTeams": true
}
```

It copies the \n

2024-07-22 18:19 UTC, ideen1 reviewed
@burtonjong Let me know once the JSON fields are also done

2024-07-24 02:48 UTC, burtonjong commented
@ideen1 hopefully tomorrow just got back from camping today

2024-07-24 20:43 UTC, burtonjong commented
Again its not tested but technically it should work - also note that i had to rename some of the fields in resource.ts for readability. I also had to create a special Type so that scoringComponents and scoringSidepots are considered arrays (or else there were type errors)

2024-07-24 20:45 UTC, burtonjong commented
![image](https://github.com/user-attachments/assets/a24c1c1f-27a3-4a20-807e-00ef94261a2c)


Here is the object that is passed to the mutation for reference

2024-07-24 20:45 UTC, burtonjong commented
![image](https://github.com/user-attachments/assets/0d4b7c91-a225-4afc-ac2e-6385715476e9)

And how it looks

2024-07-24 21:25 UTC, ideen1 commented on src/components/reset/ResetPage.tsx
> +  type Arguments = Pick<
Everything look great. Can you just elaborate on why this type was needed?

2024-07-24 21:25 UTC, ideen1 commented on src/components/reset/ResetPage.tsx
> +        // e.preventDefault(); // This will prevent the default form submit action which is to refresh the page
Remove commented code

2024-07-24 21:30 UTC, ideen1 requested changes

2024-07-24 21:30 UTC, ideen1 commented on src/components/reset/ResetPage.tsx
> +            <Label>Score Components (JSON): </Label>
Can you remove (JSON)

2024-07-24 21:30 UTC, ideen1 commented on src/components/reset/ResetPage.tsx
> +            <Label htmlFor="scoringSidepots">Scoring Sidepots (JSON): </Label>
Can you remove (JSON)

2024-07-24 21:30 UTC, ideen1 commented on src/components/reset/ResetPage.tsx
> +          <Label htmlFor="safetyCheck">Safety Check: </Label>
Rename Label to: **Enter "deletehackathon" to confirm**

```suggestion
          <Label htmlFor="safetyCheck">Enter "deletehackathon" to confirm </Label>
```

2024-07-24 21:30 UTC, ideen1 commented on src/components/reset/ResetPage.tsx
> +              required
Add placeholder that says "deletehackathon"

2024-07-25 00:02 UTC, burtonjong commented
@ideen1 in handler.ts (allan's function) it is "delete hackathon" (with a space), so that is what i put

2024-07-25 00:26 UTC, ideen1 approved these changes
LGTM!!

2024-07-25 00:29 UTC, merged