Hmt 7 judge showcase
Code-the-Change-YYC/hackathon-management-tool pull request #8
Opened 2024-02-26 22:39 UTC by burtonjong

Just need some feedback on this component. Since the name/company are beside the image it was hard to find a fitting ratio for the image/font-size (as they would overlap when the screen becomes smaller). Let me know if I should change anything or if it looks off because on mobile it does look a little small in my opinion, but if it were made any larger, if the name of the person is long enough then it would overlap with the adjacent judge. 
Mobile View:
![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/108391733/22c75cf6-3519-4644-b861-d077ef8ea589)
Desktop view below

Also, I made this component so that it fits the amount of judges (in this picture 9 judges) but should I make it so that it is 100% of the viewport width? As you can see the judging criteria is also in the viewport.
![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/108391733/338911b4-05d1-460f-8d97-86f794b2cffc)

Also because I am not the best with Next/Contentful images I am not sure what the type of image is (string, static image type, etc) so this is pretty default until we connect it to Contentful. 
![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/108391733/39baa822-7cfa-405f-9225-656010ee21c3)

2024-02-26 22:41 UTC, burtonjong commented
I also just realized I set enableLandingPage to false. I can change this before merging 
![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/108391733/10859a04-99a3-462e-8d29-72247d94f79f)

2024-02-29 06:28 UTC, ideen1 requested changes
Looks good to me just, need to set the enable Landing Page part to true :)

2024-02-29 06:28 UTC, ideen1 commented on public/images/imgplaceholder.png
11/10 Approved

2024-03-01 00:05 UTC, burtonjong commented on public/images/imgplaceholder.png
Haha thanks

2024-03-01 00:06 UTC, burtonjong commented
Just made the feature flag change

2024-03-05 07:17 UTC, ideen1 approved these changes

2024-03-07 20:34 UTC, burtonjong commented
There were merge conflicts due to page.tsx being changed from the "AboutEventTile" being merged into main. I resolved the conflicts in the github editor but for some reason it gave me an ESLint error..? So I tried rebasing from main to manually resolve the errors and yet there is still an ESLint error. 
![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/108391733/1d8b4ce8-4df5-43b1-a1f6-8aedbd2eb22d)
Is there a reason why I should switch the positions of these imports just because of the prettier extension?? Makes no sense to me but I did and I guess it fixed it... Hopefully I did not break something

2024-03-07 21:44 UTC, ideen1 commented
> There were merge conflicts due to page.tsx being changed from the "AboutEventTile" being merged into main. I resolved the conflicts in the github editor but for some reason it gave me an ESLint error..? So I tried rebasing from main to manually resolve the errors and yet there is still an ESLint error. ![image](https://private-user-images.githubusercontent.com/108391733/311026833-1d8b4ce8-4df5-43b1-a1f6-8aedbd2eb22d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDgwNDIsIm5iZiI6MTcwOTg0Nzc0MiwicGF0aCI6Ii8xMDgzOTE3MzMvMzExMDI2ODMzLTFkOGI0Y2U4LTRkZjUtNDNiMS1hMWY2LThhZWRiZDJlYjIyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QyMTQyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjUxN2JmODE3NThjNDNiZmEzZTgyOGM0MGI0ZDkyZDdiZjU4ODdhYmFkZTU3YWMyNGQwYjVkNzYzMGUzYjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FLaAD7rObkxCzVQo40Cob3QDxCbKFDKfFEqkN_EHgw8) Is there a reason why I should switch the positions of these imports just because of the prettier extension?? Makes no sense to me but I did and I guess it fixed it... Hopefully I did not break something

Hey Burton, the reason is that it’s trying to sort them according to a standard order across all files. In this case the component imports are sorted alphabetically. I agree that is has no functional difference but it helps keep the code base clean. These should be auto formatted on save. You can also run format in VSCode and it should do all these swaps for you.

2024-03-07 22:22 UTC, ideen1 approved these changes
Looks great!

2024-03-07 22:47 UTC, merged